services:
  edge-n1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sedcm-edge-${EDGE_ZONE:-B}1-n1
    restart: unless-stopped
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT:-1883}
      EDGE_ZONE: ${EDGE_ZONE:-B}
      EDGE_RACK: ${EDGE_ZONE:-B}1
      NODE_ID: ${EDGE_ZONE:-B}N1
      EXECUTOR_ID: executor-${EDGE_ZONE:-B}1-${EDGE_ZONE:-B}N1
      NODE_INTERVAL_S: ${NODE_INTERVAL_S:-5}
      ENV_INTERVAL_S: ${ENV_INTERVAL_S:-10}
      ACK_DELAY_S: ${ACK_DELAY_S:-0.5}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  edge-n2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sedcm-edge-${EDGE_ZONE:-B}1-n2
    restart: unless-stopped
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT:-1883}
      EDGE_ZONE: ${EDGE_ZONE:-B}
      EDGE_RACK: ${EDGE_ZONE:-B}1
      NODE_ID: ${EDGE_ZONE:-B}N2
      EXECUTOR_ID: executor-${EDGE_ZONE:-B}1-${EDGE_ZONE:-B}N2
      NODE_INTERVAL_S: ${NODE_INTERVAL_S:-5}
      ENV_INTERVAL_S: ${ENV_INTERVAL_S:-10}
      ACK_DELAY_S: ${ACK_DELAY_S:-0.5}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  edge-n3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sedcm-edge-${EDGE_ZONE:-B}2-n3
    restart: unless-stopped
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT:-1883}
      EDGE_ZONE: ${EDGE_ZONE:-B}
      EDGE_RACK: ${EDGE_ZONE:-B}2
      NODE_ID: ${EDGE_ZONE:-B}N3
      EXECUTOR_ID: executor-${EDGE_ZONE:-B}2-${EDGE_ZONE:-B}N3
      NODE_INTERVAL_S: ${NODE_INTERVAL_S:-5}
      ENV_INTERVAL_S: ${ENV_INTERVAL_S:-10}
      ACK_DELAY_S: ${ACK_DELAY_S:-0.5}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  edge-n4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sedcm-edge-${EDGE_ZONE:-B}2-n4
    restart: unless-stopped
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT:-1883}
      EDGE_ZONE: ${EDGE_ZONE:-B}
      EDGE_RACK: ${EDGE_ZONE:-B}2
      NODE_ID: ${EDGE_ZONE:-B}N4
      EXECUTOR_ID: executor-${EDGE_ZONE:-B}2-${EDGE_ZONE:-B}N4
      NODE_INTERVAL_S: ${NODE_INTERVAL_S:-5}
      ENV_INTERVAL_S: ${ENV_INTERVAL_S:-10}
      ACK_DELAY_S: ${ACK_DELAY_S:-0.5}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
